name: Angular & ASP.NET Core CI/CD

env:
  configuration: 'Release' 

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github
  pull_request:
    branches: [ master ]
  workflow_dispatch:    

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - name: Publish
      run: dotnet publish --no-build --configuration ${{ env.configuration }} --output Publish --verbosity normal
      working-directory: src
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2           
      with:
        # Artifact name
        name: angular
        # A file, directory or wildcard pattern that describes what to upload
        path: src/Publish
        # The desired behavior if no files are found using the provided path.
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        # Artifact name
        name: angular
        # Destination path
        path: Deploy
